uint64 timestamp			# time since system start (microseconds)

uint64 current_time		# current time  (ms)
uint64 start_time		# scenario start time (ms)
uint32 seq			    # scenario sequence 
float32 offset_x		# position offset_x (m)
float32 offset_y		# position offset_y (m)
uint8  ready_sc_file    # 1: scenario file ready, 2: scenario file length err, 3: scenario file crc err, 4: scenario payload header err
