uint64 timestamp            # time since system start (microseconds)
float32 event_time          # scenario event time
uint8 event_type            # scenario event type
uint8 cmd_type              # scenario cmd type
float32 x                   # scenario setpoint x
float32 y                   # scenario setpoint y
float32 z                   # scenario setpoint z
uint8 led_r                 # scenario LED R
uint8 led_g                 # scenario LED G
uint8 led_b                 # scenario LED B
bool is_scenario_active       # True from the start of the scenario arm event until the landing event
